name: Build

on:
  push:
  pull_request:

jobs:
  assemble:
    name: Assemble
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew assembleRelease
        # Upload all build artifacts in separate steps. This can be shortened once https://github.com/actions/upload-artifact/pull/354 is merged.
      - name: Upload artifact phone-libre-arm64-v8a.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-arm64-v8a.apk
          path: ./app/phone/build/outputs/apk/libre/release/*arm64-v8a*.apk
      - name: Upload artifact phone-libre-armeabi-v7a.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-armeabi-v7a.apk
          path: ./app/phone/build/outputs/apk/libre/release/*armeabi-v7a*.apk
      - name: Upload artifact phone-libre-x86_64.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-x86_64.apk
          path: ./app/phone/build/outputs/apk/libre/release/*x86_64*.apk
      - name: Upload artifact phone-libre-x86.apk
        uses: actions/upload-artifact@v4
        with:
          name: phone-libre-x86.apk
          path: ./app/phone/build/outputs/apk/libre/release/*x86*.apk
      - name: Upload artifact tv-libre-arm64-v8a.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-arm64-v8a.apk
          path: ./app/tv/build/outputs/apk/libre/release/*arm64-v8a*.apk
      - name: Upload artifact tv-libre-armeabi-v7a.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-armeabi-v7a.apk
          path: ./app/tv/build/outputs/apk/libre/release/*armeabi-v7a*.apk
      - name: Upload artifact tv-libre-x86_64.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-x86_64.apk
          path: ./app/tv/build/outputs/apk/libre/release/*x86_64*.apk
      - name: Upload artifact tv-libre-x86.apk
        uses: actions/upload-artifact@v4
        with:
          name: tv-libre-x86.apk
          path: ./app/tv/build/outputs/apk/libre/release/*x86*.apk
